#! /bin/sh
set -e

PROGNAME=$(basename $0)
COMMAND=./doflash.sh
BUILDDIR=build
NOCLEANUP=""
usage()
{
    cat >&2 <<EOF
Deploy a tegraflash image to a machine connected via local USB
and in recovery mode.
Usage: $PROGNAME --machine <MACHINE> --image <IMAGE>
Options:
    -h, --h             Print this usage message
    -m, --machine       Set the MACHINE used for this script
    -i, --image         Set the IMAGE used for this script
    -b, --builddir      Set the build dir used for deployment: default ${BUILDDIR}
    -n, --nocleanup     Don't cleanup the temp directory after successful completion
    -c, --command       Set the command to use when flashing: default ${COMMAND}
                        other options:
                            "sudo ./initrd-flash"
                            "./initrd-flash"
Examples:
- To deploy a demo-image-base image for jetson-xavier-nx-devkit machine:
  $ $0 --machine jetson-xavier-nx-devkit  --image demo-image-base
EOF
}

# get command line options
SHORTOPTS="hm:i:b:c:n"
LONGOPTS="help,machine:,image:,builddir:,command:,nocleanup"

ARGS=$(getopt --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@" )
if [ $? != 0 ]; then
   usage
   exit 1
fi

eval set -- "$ARGS"
while true;
do
    case $1 in
        -h | --help)       usage; exit 0 ;;
        -m | --machine)    MACHINE="$2"; shift 2;;
        -i | --image)      IMAGE="$2"; shift 2;;
        -b | --builddir)   BUILDDIR="$2"; shift 2;;
        -n | --nocleanup)  NOCLEANUP="true"; shift 1;;
        -c | --command)    COMMAND="$2"; shift 2;;
        -- )               shift; break ;;
        * )                break ;;
    esac
done

if [ -z "$MACHINE" ]; then
    echo "You must specify a machine"
    usage
    exit 1
fi

if [ -z "$IMAGE" ]; then
    echo "You must specify an image"
    usage
    exit 1
fi

echo "Using machine ${MACHINE} image ${IMAGE} builddir ${BUILDDIR} and command ${COMMAND}"
deployfile=${IMAGE}-${MACHINE}.tegraflash.tar.gz
scriptdir=$(realpath $(dirname $0))
tmpdir=`mktemp -d /tmp/oe4t-tegraflash-XXXXX`
echo "Using temp directory $tmpdir"
currentdir=$(realpath .)
cd $tmpdir
cp $scriptdir/../../../${BUILDDIR}/tmp/deploy/images/${MACHINE}/$deployfile .
tar -xvf $deployfile
set +e
${COMMAND}
rc=$?
cd $currentdir
if [ $rc -ne 0 ]; then
    if [ ! -e /etc/udev/rules.d/??-oe4t.rules ]; then
        echo "No rules file exists and flash failed."
        echo "You may need to run setup-udev-rules"
        echo "Or run this script as root"
    fi
    echo "${COMMAND} failed, see temp directory at ${tmpdir}"
else
    if [ -z "${NOCLEANUP}" ]; then
        echo "Cleaning up after success, removing temp directory $tmpdir"
        rm -rf $tmpdir
    else
        echo "Skipping cleanup after success, see results in directory at ${tmpdir}"
    fi
fi
exit $rc
